---
initChownData:
  enabled: false
datasources: 
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server.prometheus.svc.cluster.local
     isDefault: true
   - name: Loki
     type: loki
     url: http://loki-gateway.loki.svc.cluster.local
     isDefault: false
   - name: Tempo
     type: tempo
     url: http://tempo.tempo.svc.cluster.local:3200
     isDefault: false 
     
persistence:
  type: pvc
  enabled: true
ingress:
  enabled: true
  ingressClassName: public
  hosts:
    - grafana.local

adminUser: admin
adminPassword: P@ssw0rd

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'cluster'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    k8s-cluster-dashboard:
      gnetId: 16674
      revision: 1
      datasource: Prometheus   